name: MAGMA Music Auto Restart

on:
  workflow_run:
    workflows:
      - "MAGMA Music"
    types:
      - completed

permissions:
  actions: write
  contents: read

jobs:
  restart:
    if: |
      github.event.workflow_run.conclusion == 'failure' ||
      github.event.workflow_run.conclusion == 'timed_out'

    runs-on: ubuntu-latest

    steps:

      - name: Wait
        run: sleep 20

      - name: Restart MAGMA Music
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          gh workflow run main.yml \
            --repo "${{ github.repository }}" \
            --ref main

          echo "✅ MAGMA Music restarted."